apiVersion: v1
kind: Secret # Secrets for Azure DevOps authentication
metadata:
  name: {{ .Release.Name }}-pipeline-auth
  namespace: devopsagent
data:
  AZP_URL: TO_BE_DEFINED
  AZP_POOL: {{ .Values.data.azp_pool }}
  AZP_TOKEN: TO_BE_DEFINED
